### ISSUE TITLE
Add packageJsonPath

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/pin-dependencies-checker#6]
Will be good for the cases where you have top level package.json but also nested folders.

**Comment by amercier** [comment]
That would also be nice for supporting mono-repository using npm [workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces).

**Comment by raulfdm** [comment]
@amercier , On v2 it works in any monorepo.

That's because now the lib is scanning for all package json in the cwd :)
